cloud_id = "b1gh0n7kf5b5nrdf2il4"
folder_id = "b1gndtk21ufe5qbljq5h"
zone = "ru-central1-a"
image_id = "fd82nqd7gv5p6gdpcqfr"
public_key_path = "/Users/kingascalon/.ssh/yc.pub"
subnet_id = "e9bo0v9bqn70k7e15tjr"
service_account_key_file = "/Users/kingascalon/Desktop/Ascalonking_infra/terraform/key.json"
private_key_for_conn_provisioner = "/Users/kingascalon/.ssh/yc"